# Generated by Django 3.1.2 on 2020-10-19 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeJuegos', '0002_auto_20201018_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='videoJuego',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.plataforma'),
        ),
    ]
