# Generated by Django 3.1.2 on 2020-10-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=20)),
                ('stock', models.IntegerField()),
                ('plataforma', models.TextField(max_length=30)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
