# Generated by Django 3.1.2 on 2020-10-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeJuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBoleta', models.DecimalField(decimal_places=0, max_digits=13)),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField(max_length=100)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('encargado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=20)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precioCosto', models.DecimalField(decimal_places=0, max_digits=20)),
                ('precioVenta', models.DecimalField(decimal_places=0, max_digits=20)),
                ('stock', models.IntegerField()),
                ('desarrolladora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.desarrolladora')),
            ],
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='videoJuego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.videojuego'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='videoJuego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.videojuego'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeJuegos.sucursal'),
        ),
    ]
