# Generated by Django 3.1.2 on 2020-11-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeJuegos', '0003_auto_20201018_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='boleta',
            name='idBoleta',
            field=models.IntegerField(),
        ),
    ]
