# Generated by Django 3.1.2 on 2020-11-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeJuegos', '0004_auto_20201103_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
