# Generated by Django 3.1.2 on 2020-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeJuegos', '0006_videojuego_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('categoria', models.TextField()),
                ('plataforma', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='juegos')),
            ],
        ),
    ]
